name: Publish to GitHub Release

on:
  workflow_dispatch: # Allows manual triggering
  release:
    types: [published] # Triggers on GitHub release publication

permissions:
  contents: write # Grant write permissions to repository contents

jobs:
  build-and-release:
    name: Build and Attach to Release
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Step 3: Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Step 4: Verify pnpm Installation
      - name: Verify pnpm Installation
        run: pnpm --version

      # Step 5: Install dependencies
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      # Step 6: Navigate to the Package and Build
      - name: Build Project
        run: pnpm build

      # Step 7: Zip the dist folder for upload
      - name: Prepare Release Assets
        working-directory: packages/ord-connect
        run: zip -r dist.zip dist index.d.ts package.json

      # Step 8: Upload Assets to GitHub Release
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./packages/ord-connect/dist.zip
          asset_name: ord-connect-dist.zip
          asset_content_type: application/zip
