name: Publish to GitHub Release

on:
  workflow_dispatch: # Allows manual triggering
  release:
    types: [published] # Triggers on GitHub release publication

jobs:
  build-and-release:
    name: Build and Attach to Release
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js and pnpm
      - name: Set up Node.js and pnpm
        run: corepack enable pnpm
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Replace with your required Node.js version
          cache: pnpm

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      # Step 4: Navigate to the Package and Build
      - name: Build Project
        working-directory: packages/ord-connect
        run: pnpm build

      # Step 5: Zip the dist folder for upload
      - name: Prepare Release Assets
        working-directory: packages/ord-connect
        run: zip -r dist.zip dist index.d.ts package.json

      # Step 6: Upload Assets to GitHub Release
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./packages/ord-connect/dist.zip
          asset_name: ord-connect-dist.zip
          asset_content_type: application/zip
